### ISSUE TITLE
[Feature] Open in separate window 

### ISSUE THREAD

**Issue by UwQ-Official** [Thomasims/tdconsole#1]
Could you please make it so that the console opens in a window of its own process (not as a child of `teardown.exe`).

This would also allow for use of the new [Terminal App](https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-US&gl=US) instead of the `system32\cmd.exe` one; The new app has an option allowing the window to remain open even after the program crashes/gets closed, which can be useful for when you have to figure out why the game crashed

**Comment by Thomasims** [comment]
No. I understand the appeal in that feature but the point of this DLL is its simplicity and I don't have time to look into how one would achieve this anyway.
